// This file was generated by Birch.Swagger.ProxyGenerator
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;
using Birch.Swagger.ProxyGenerator.IntegrationTest;

namespace Birch.Swagger.ProxyGenerator.IntegrationTest
{
    public abstract class AutofacIntegrationTestBaseProxy
    {
        protected readonly Uri BaseUrl;
        public readonly List<Action<BeforeRequestActionArgs>> GlobalBeforeRequestActions;
        public readonly List<Action<IWebProxyResponse>> GlobalAfterRequestActions;
        public readonly List<Action<BeforeRequestActionArgs>> BeforeRequestActions;
        public readonly List<Action<IWebProxyResponse>> AfterRequestActions;

        protected AutofacIntegrationTestBaseProxy(Uri baseUrl)
        {
            BaseUrl = baseUrl;
            GlobalBeforeRequestActions = new List<Action<BeforeRequestActionArgs>>();
            GlobalAfterRequestActions = new List<Action<IWebProxyResponse>>();
            BeforeRequestActions = new List<Action<BeforeRequestActionArgs>>();
            AfterRequestActions = new List<Action<IWebProxyResponse>>();
        }

        /// <summary>
        /// Builds the HTTP client.
        /// </summary>
        /// <returns></returns>
        protected virtual HttpClient BuildHttpClient()
        {
            var httpClient = new HttpClient
            {
                BaseAddress = BaseUrl
            };
            return httpClient;
        }
        
        /// <summary>
        /// Runs before the request asynchronous.
        /// </summary>
        /// <param name="requestUri">The request URI.</param>
        /// <param name="requestMethod">The request method.</param>
        /// <returns></returns>
        public virtual Task BeforeRequestAsync(BeforeRequestActionArgs actionArgs)
        {
            foreach (var globalBeforeRequestAction in GlobalBeforeRequestActions)
            {
                globalBeforeRequestAction.Invoke(actionArgs);
            }

            foreach (var beforeRequestAction in BeforeRequestActions)
            {
                beforeRequestAction.Invoke(actionArgs);
            }
            BeforeRequestActions.Clear();
            return Task.FromResult(0);
        }

        /// <summary>
        /// Runs After the request asynchronous.
        /// </summary>
        /// <param name="response">The response.</param>
        /// <param name="webProxyResponse">The web proxy response.</param>
        /// <returns></returns>
        public virtual async Task AfterRequestAsync(IWebProxyResponse webProxyResponse)
        {
            foreach (var globalAfterRequestAction in GlobalAfterRequestActions)
            {
                globalAfterRequestAction.Invoke(webProxyResponse);
            }

            foreach (var afterRequestAction in AfterRequestActions)
            {
                afterRequestAction.Invoke(webProxyResponse);
            }
            AfterRequestActions.Clear();

            if (webProxyResponse.Response.IsSuccessStatusCode)
            {
                return;
            }

            try
            {
                var content = await webProxyResponse.Response.Content.ReadAsStringAsync().ConfigureAwait(false);
                webProxyResponse.Exception = new SimpleHttpResponseException(webProxyResponse.Response.StatusCode, content);
            }
            finally
            {
                webProxyResponse.Response.Content?.Dispose();
            }
        }

        /// <summary>
        /// Appends the query.
        /// </summary>
        /// <param name="currentUrl">The current URL.</param>
        /// <param name="paramName">Name of the parameter.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        protected string AppendQuery(string currentUrl, string paramName, string value)
        {
            if (currentUrl.Contains("?"))
            {
                currentUrl += string.Format("&{0}={1}", paramName, Uri.EscapeUriString(value));
            }
            else
            {
                currentUrl += string.Format("?{0}={1}", paramName, Uri.EscapeUriString(value));
            }
            return currentUrl;
        }
        public class WebProxyResponse<T> : IWebProxyResponse
        {
            public HttpResponseMessage Response { get; set; }
            public TimeSpan RequestDuration { get; set; }
            public Type ExpectedResponseType { get; set; }
            public T Body { get; internal set; }
            public Exception Exception { get; set; }
        }
        public class WebProxyResponse : IWebProxyResponse
        {
            public HttpResponseMessage Response { get; set; }
            public TimeSpan RequestDuration { get; set; }
            public Type ExpectedResponseType { get; set; }
            public Exception Exception { get; set; }
        }
        public interface IWebProxyResponse
        {
            HttpResponseMessage Response { get; set; }
            TimeSpan RequestDuration { get; set; }
            Type ExpectedResponseType { get; set; }
            Exception Exception { get; set; }
        }
        public class BeforeRequestActionArgs
        {
            public string Uri { get; set; }
            public string ActionName { get; set; }
            public string Method { get; set; }
        }

        public class SimpleHttpResponseException : Exception
        {
            public HttpStatusCode StatusCode { get; private set; }

            public SimpleHttpResponseException(HttpStatusCode statusCode, string content)
            : base(content)
            {
                StatusCode = statusCode;
            }
        }
    }
}
